# Generated by Django 5.0.4 on 2024-04-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
